development:
  clients:
    default:
      database: tenex
      hosts:
        - localhost:27027
      options:
        server_selection_timeout: 1

production:
  clients:
    default:
      database: tenex
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 5
